Name = "ArvanCloud"
Description = ''''''
URL = "https://www.arvancloud.com"
Code = "arvancloud"
Since = "v4"

Example = '''
ARVANCLOUD_API_KEY=Apikey XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX \
lego --dns arvancloud --domains domain.com --email my@email.com run
'''

[Configuration]
  [Configuration.Credentials]
    ARVANCLOUD_API_KEY = "API key"
  [Configuration.Additional]
    ARVANCLOUD_POLLING_INTERVAL = "Time between DNS propagation check"
    ARVANCLOUD_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    ARVANCLOUD_TTL = "The TTL of the TXT record used for the DNS challenge"
    ARVANCLOUD_HTTP_TIMEOUT = "API request timeout"
    ARVANCLOUD_SEQUENCE_INTERVAL = "Interval between iteration"

[Links]
  API = "https://www.arvancloud.com/docs/api/cdn/4.0"